### PR TITLE
Initial libhooker support

### PR DESCRIPTION
**Pull request by coolstar**
WIP. Only supports Objective-C (no support for hookf)

### CODE REVIEW

**Comment by kirb** [comment]
Thanks heaps, going to work on this when I get an opportunity to. Also would like to unify the code with the substrate generator as much as possible so we can avoid duplication, given the logic is very similar aside from function hooking taking an array. 

I’m considering splitting function and method hook generators, so they can be mixed as needed. `generator` config would set both `objc_generator` and `func_generator`. That also opens the opportunity for other func hook libraries like fishhook. Might leave that till a later date though depending if I feel the extra refactoring work will be quick or not. 

Once merged, on the Theos side we’ll make deploy target >=15.0 default to libhooker generator rather than substrate.

**Comment by bukaixyz** [comment]
good

**Comment by uroboro** [comment]
If we add a Group "subclass" and modify how the function initializers are formatted and used, we can add support for `LHHookFunctions`. Here's the diff for the necessary changes:
https://gist.github.com/uroboro/d5c845832cffb98940cc23e9edbd72d8

Please add them and let me know if the formatting is correct, based on https://gist.github.com/coolstar/902bb1a4664f3d987ae954aaf39415f9.

**Review by uroboro — APPROVED** [review]
It should be good to go now

**Pull request merged**
